### ISSUE TITLE
Error during install from conda

### ISSUE THREAD

**Issue by jbruxaux** [ksamuk/pixy#86]
Hi!

I'm trying to install pixy from conda, following the very clear explanations on the readthedocs.io website. But I get an error when I type "pixy --help" at the end:

```
Traceback (most recent call last):
  File "/home/j/jbruxaux/miniconda3/envs/pixy/bin/pixy", line 7, in <module>
    from pixy.__main__ import main
  File "/home/j/jbruxaux/miniconda3/envs/pixy/lib/python3.8/site-packages/pixy/__main__.py", line 6, in <module>
    import allel
  File "/home/j/jbruxaux/miniconda3/envs/pixy/lib/python3.8/site-packages/allel/__init__.py", line 4, in <module>
    from .model.ndarray import *
  File "/home/j/jbruxaux/miniconda3/envs/pixy/lib/python3.8/site-packages/allel/model/ndarray.py", line 18, in <module>
    from allel.opt.model import genotype_array_pack_diploid, genotype_array_unpack_diploid, \
  File "allel/opt/model.pyx", line 1, in init allel.opt.model
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

```
I tried to install an older version of numpy, as suggested here #82, but it didn't help, I get the same error message. 
I am using python 3.8.17.
Any idea?

Thanks in advance!

Jade

**Comment by jbruxaux** [comment]
I found a solution. I upgraded numpy and scipy using pip instead of conda, and it works now. I leave the issue opened, in case it helps someone else.

**Comment by jgroh** [comment]
Hi Kieran, 

Just to add in case it's relevant, I'm seeing a similar error after installing from conda according to https://pixy.readthedocs.io/en/latest/installation.html and running `pixy --help` (not entirely sure it's the same issue):

```
File "/home/jgroh/.conda/envs/pixy2/bin/pixy", line 7, in <module>
    from pixy.__main__ import main
File "/home/jgroh/.conda/envs/pixy2/lib/python3.8/site-packages/pixy/__main__.py", line 6, in <module>
    import allel
File "/home/jgroh/.conda/envs/pixy2/lib/python3.8/site-packages/allel/__init__.py", line 5, in <module>
    from .model.chunked import *
File "/home/jgroh/.conda/envs/pixy2/lib/python3.8/site-packages/allel/model/chunked.py", line 24, in <module>
    from allel import chunked as _chunked
File "/home/jgroh/.conda/envs/pixy2/lib/python3.8/site-packages/allel/chunked/__init__.py", line 52, in <module>
    import h5py as _h5py
File "/home/jgroh/.conda/envs/pixy2/lib/python3.8/site-packages/h5py/__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
File "h5py/h5t.pxd", line 14, in init h5py._conv
File "h5py/h5t.pyx", line 293, in init h5py.h5t
File "/home/jgroh/.conda/envs/pixy2/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
```

If I then do `pip install numpy==1.21` within the conda environment, it seems to resolve. 

Jeff
